bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

freshNow_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('aboutUs/', include('aboutUs.urls')),
    path('wishlist/', include('wishlist.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_products, name='products'),
    path('<int:product_id>/', views.product_detail, name='product_detail'),
    path('add/', views.add_product, name='add_product'),
    path('edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete/<int:product_id>/', views.delete_product,
         name='delete_product'),
    path('add_review/<int:product_id>/', views.add_review, name='add_review'),
    path('edit_review/<int:review_id>/', views.edit_review,
         name='edit_review'),
]

products/models.py
from django.db import models


class Category(models.Model):

    class Meta:
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=200)
    friendly_name = models.CharField(max_length=200, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Product(models.Model):
    category = models.ForeignKey(
        'Category', null=True, blank=True, on_delete=models.SET_NULL)
    sku = models.CharField(max_length=254, null=True, blank=True)
    name = models.CharField(max_length=254)
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    rating = models.DecimalField(
        max_digits=6, decimal_places=2, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    calories = models.DecimalField(
        max_digits=6, null=True, blank=True, decimal_places=0)
    is_spicy = models.BooleanField(default=False, null=True, blank=True)

    def __str__(self):
        return self.name

reviews/models.py
from django.db import models
from profiles.models import UserProfile
from products.models import Product


class Reviews(models.Model):

    """
    Stores review details in the database
    """
    RATING = [
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    ]

    profile_user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rating = models.IntegerField(choices=RATING)
    review = models.TextField(max_length=1500)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'User: {self.profile_user} | Product: {self.product} | \
                    Rating: {self.rating}'

products/forms.py
from django import forms
from .widgets import CustomClearableFileInput
from .models import Product, Category


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

    image = forms.ImageField(label='Image', required=False,
                             widget=CustomClearableFileInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        friendly_names = [(c.id, c.get_friendly_name()) for c in categories]

        self.fields['category'].choices = friendly_names
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-black rounded-0'

products/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from .models import Product, Category
from .forms import ProductForm
from django.db.models import Avg
from django.db.models import Q
from reviews.models import Reviews
from reviews.forms import ReviewForm
from profiles.models import UserProfile
from wishlist.models import Wishlist


def all_products(request):
    """ A view to show all products, including sorting and search queries """

    products = Product.objects.all()
    query = None
    categories = None
    sort = None
    direction = None

    if request.GET:

        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                products = products.annotate(lower_name=Lower('name'))
            if sortkey == 'category':
                sortkey = 'category__name'

            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            products = products.order_by(sortkey)

        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            products = products.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(
                    request, "You didn't enter any search criteria!")
                return redirect(reverse('products'))

            queries = Q(name__icontains=query) | Q(
                description__icontains=query)
            products = products.filter(queries)

    current_sorting = f'{sort}_{direction}'

    wishlist = None
    if request.user.is_authenticated:
        user = get_object_or_404(UserProfile, user=request.user)
        wishlist = Wishlist.objects.filter(profile_user=user)

    context = {
        'products': products,
        'search_term': query,
        'current_categories': categories,
        'current_sorting': current_sorting,
        'wishlist': wishlist,
    }

    return render(request, 'products/products.html', context)


def product_detail(request, product_id):
    """ A view to show individual product details """

    product = get_object_or_404(Product, pk=product_id)
    reviews = Reviews.objects.all().filter(product=product)
    avg_rating = reviews.aggregate(Avg('rating'))['rating__avg']
    if avg_rating is not None:
        # round to the nearest 0.5 value
        avg_rating = round(avg_rating * 2) / 2

    if not request.user.is_authenticated:
        template = 'products/product_detail.html'

        context = {
            'product': product,
            'reviews': reviews,
            'avg_rating': avg_rating,
            }
        return render(request, template, context)
    else:
        product = get_object_or_404(Product, pk=product_id)
        profile_user = get_object_or_404(UserProfile, user=request.user)
        # find a match to the product and user
        wishlist = Wishlist.objects.filter(
                   profile_user=profile_user, product=product_id)

        form = ReviewForm()
        reviews = Reviews.objects.all().filter(product=product)
        avg_rating = reviews.aggregate(Avg('rating'))['rating__avg']
        product.rating = avg_rating

        template = 'products/product_detail.html'

        context = {
           'product': product,
           'profile_user': profile_user,
           'wishlist': wishlist,
           'form': form,
           'avg_rating': avg_rating,
        }

        return render(request, template, context)


@login_required
def add_product(request):
    """ Add a product to the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request, 'Successfully added product!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(
                request, 'Add product failed.Please ensure the form is valid.')
    else:
        form = ProductForm()

    template = 'products/add_product.html'
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def edit_product(request, product_id):
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))
    product = get_object_or_404(Product, pk=product_id)
    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, "Product successfully updated")
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(
                request, 'Failed to update. Please ensure the form is valid.')
    else:
        form = ProductForm(instance=product)
        messages.info(request, f'You are editing {product.name}')

    template = 'products/edit_product.html'
    context = {
        'form': form,
        'product': product,
    }

    return render(request, template, context)


@login_required
def delete_product(request, product_id):
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    """ Delete a product from the store """
    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    messages.success(request, 'Product deleted!')
    return redirect(reverse('products'))


@login_required
def add_review(request, product_id):
    """
    A view to allow the user to add a review to a product
    """
    user = get_object_or_404(UserProfile, user=request.user)
    product = get_object_or_404(Product, pk=product_id)

    if request.user.is_authenticated:
        if request.method == 'POST':
            form = ReviewForm(request.POST)
            if form.is_valid():
                review = form.save(commit=False)
                review.product = product
                review.profile_user = user
                review.save()
                messages.info(request, 'Your review was successful')
                return redirect(reverse('product_detail', args=[product.id]))
            else:
                messages.error(
                    request, 'Failed to add your review')
    context = {
        'form': form,
    }

    return render(request, context)


@login_required
def edit_review(request, review_id):
    """
    A view to allow the users to edit their own review
    """

    review = get_object_or_404(Reviews, pk=review_id)
    product = review.product

    if request.method == 'POST':
        form = ReviewForm(request.POST, instance=review)
        if form.is_valid():
            form.save()
            messages.success(request, 'Review has been updated')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(
                request, 'Review edit failed, Please try again')

    else:
        form = ReviewForm(instance=review)

    messages.info(request, 'You are editing your review')
    template = 'products/product_detail.html'
    context = {
        'form': form,
        'review': review,
        'product': product,
        'edit': True,
    }
    return render(request, template, context)

products/templates/products/add_product.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-6">
                <hr>
                <h2 class="logo-font mb-4">Product Management</h2>
                <h5 class="text-light">Add a Product</h5>
                <hr>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-6">
                <form method="POST" action="{% url 'add_product' %}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                    {% if field.name != 'image' %}
                        {{ field | as_crispy_field }}
                    {% else %}
                        {{ field }}
                    {% endif %}
                {% endfor %}
                    <div class="text-right">
                        <a class="btn order-button" href="{% url 'products' %}">Cancel</a>
                        <button class="btn order-button" type="submit">Add Product</button>
                    </div>
                </form>
            </div>            
        </div>
    </div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
        $('#new-image').change(function() {
            var file = $('#new-image')[0].files[0];
            $('#filename').text(`Image will be set to: ${file.name}`);
        });
    </script>
{% endblock %}

products/templates/products/edit_product.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}

<div class="container">
    <div class="row ">
        <div class="col-12 col-md-6">
            <hr>
            <h2 class="logo-font mb-4 text-light">Product Management</h2>
            <h5 class="text-light">Edit a Product</h5>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-12 col-md-6">
            <form method="POST" action="{% url 'edit_product' product.id %}" class="form mb-2"
                enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                {% if field.name != 'image' %}
                {{ field | as_crispy_field }}
                {% else %}
                {{ field }}
                {% endif %}
                {% endfor %}
                <div class="text-right">
                    <a class="btn order-button" href="{% url 'products' %}">Cancel</a>
                    <button class="btn order-button" type="submit">Update Product</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script>
        $('#new-image').change(function() {
            var file = $('#new-image')[0].files[0];
            $('#filename').text(`Image will be set to: ${file.name}`);
        });
    </script>
{% endblock %}

products/templates/products/product_detail.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}


{% block content %}

<div class="container-fluid product-container text-light">
    <div class="row text-center">
        <div class="col-12 col-md-6 col-lg-4 ms-lg-5 ">
            <div class="image-container my-5">
                {% if product.image %}
                <a href="{{ product.image.url }}" target="_blank">
                    <img class="card-img-top product-card img-fluid" src="{{ product.image.url }}"
                        alt="{{ product.name }}">
                </a>
                {% else %}
                <a href="">
                    <img class="card-img-top product-card img-fluid" src="{{ MEDIA_URL }}noimage.png"
                        alt="{{ product.name }}">
                </a>
                {% endif %}
            </div>
            <div class="d-flex flex-grow-1 justify-content-center align-items-center mb-4">
                <p class="text-center">
                    {% if wishlist %}
                    <span class="text-center">Remove from Wishlist: </span>
                    <a href="{% url 'delete_wishlist_item' product.id %}">
                        <i class="fas fa-heart heart-icon"></i>
                    </a>
                    {% else %}
                    <span class="text-light">Add to Wishlist: </span>
                    <a class="wishlist_btn hvr-grow"
                        href="{% if user.is_authenticated %}{% url 'add_to_wishlist' product.id %}{% else %}{% url 'account_login' %}{% endif %}">
                        <i class="far fa-heart heart-icon mt-3"></i>
                    </a>
                    {% endif %}
                </p>
            </div>
        </div>

        <div class="col-12 col-md-6 col-lg-4 offset-lg-2">
            <div class="product-details-container mb-5 me-lg-5">
                <div class="product-layout">
                    <p class="mb-2 fs-4 mt-lg-5">{{ product.name }}</p>

                    <p class="fs-5">£{{ product.price }}</p>
                    {% if product.rating %}
                    <p class="rating"><i class="fas fa-star me-2"></i>{{ avg_rating }} / 5 </p>
                    {% else %}
                    <p class="text-light">No Rating</p>
                    {% endif %}
                    {% if request.user.is_superuser %}
                    <small class="ml-3">
                        <a href="{% url 'edit_product' product.id %}" class="btn btn-sm btn-light">Edit</a>
                        <a class="btn btn-sm btn-light" href="{% url 'delete_product' product.id %}">Delete</a>
                    </small>
                    {% endif %}
                    <p class="mt-3">{{ product.description }}</p>

                    <form class="form" name="redirect_url" action="{% url 'add_to_bag' product.id %}" method="POST">
                        {% csrf_token %}
                        <div class="form-row text-center">
                            {% with product.is_spicy as s %}
                            {% if s %}
                            <div class="col-12 text-center">
                                <strong>Spicy:</strong>
                                <select class="form-control spicy-control rounded-0 w-50" name="product_spicy"
                                    id='id_product_spicy'>
                                    <option value="mild">Mild</option>
                                    <option value="medium">Medium</option>
                                    <option value="hot" selected>Hot</option>
                                </select>
                            </div>
                        </div>
                        {% endif %}
                        <div class="col-12">
                            <div class="col-12">
                                <p class="mt-3"><strong>Quantity:</strong></p>
                                <div class="form-group w-50 quantity-control">
                                    <div class="input-group">
                                        <div class="input-group-prepend ms-4">
                                            <button class="decrement-qty btn btn-dark btn-quantity rounded-0"
                                                data-item_id="{{ product.id }}" id="decrement-qty_{{ product.id }}">
                                                <span class="icon">
                                                    <i class="fas fa-minus"></i>
                                                </span></button>
                                        </div>
                                        <input class="form-control qty_input mb-3" type="number" name="quantity"
                                            value="1" min="1" max="99" data-item_id="{{ product.id }}"
                                            id="id_qty_{{ product.id }}">
                                        <div class="input-group-append">
                                            <button class="increment-qty btn btn-dark  rounded-0"
                                                data-item_id="{{ product.id }}" id="increment-qty_{{ product.id }}">
                                                <span class="icon">
                                                    <i class="fas fa-plus"></i>
                                                </span>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-12">
                            <a href="{% url 'products' %}" class="btn btn-outline-dark mt-5">
                                <span class="icon">
                                    <i class="fas fa-chevron-left"></i>
                                </span>
                                <span class="btn btn-light">Back to meals</span>
                            </a>
                            <input type="submit" class="btn btn-light mt-5" value="Order Now">
                        </div>
                    </form>
                    {% endwith %}
                </div>
            </div>
        </div>
    </div>
</div>


<div id="reviews" class="row">
    <div class="col-12 col-md-10 col-lg-4 offset-lg-4 mt-5 text-left">
        <h2 class="text-light font-weight-bold mt-5">Reviews</h2>
        {% if request.user.is_authenticated %}
        {% if edit %}
        <!-- Edit Review Form -->
        <form method="POST" action="{% url 'edit_review' review.id %}#reviews">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="text-right">
                <button class="btn order-button font-weight-bold" type="submit">Update Review</button>
            </div>
        </form>
        {% else %}
        <!--Review Form -->
        <form method="POST" action="{% url 'add_review' product.id %}">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="text-right">
                <button class="btn order-button font-weight-bold" type="submit">Submit Review</button>
            </div>
        </form>
        {% endif %}
        {% else %}
        <p class="small"> You must have an account or be logged in to leave a review.</p>
        {% endif %}
    </div>
</div>
<!-- Showing all product reviews-->
{% for review in product.reviews_set.all %}
<div class="card review-container mx-5 my-2">
    <!-- Edit Review Button-->

    <div class="card-body review-body">
        {% if review.rating == 5 %}
        <p>
            <small class="text-warning">
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>

            </small>
        </p>

        {% elif review.rating == 4 %}
        <p>
            <small class="text-warning">
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="far fa-star"></i>
            </small>
        </p>
        {% elif review.rating == 3 %}
        <p>
            <small class="text-warning">
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="far fa-star"></i>
                <i class="far fa-star"></i>
            </small>
        </p>
        {% elif review.rating == 2 %}
        <p>
            <small class="text-warning">
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="far fa-star"></i>
                <i class="far fa-star"></i>
                <i class="far fa-star"></i>
            </small>
        </p>
        {% elif review.rating == 1 %}
        <p>
            <small class="text-warning">
                <i class="fas fa-star"></i>
                <i class="far fa-star"></i>
                <i class="far fa-star"></i>
                <i class="far fa-star"></i>
                <i class="far fa-star"></i>
            </small>
        </p>
        {% else %}
        <p>
            <small class="text-light">
                No Reviews
            </small>
        </p>
        {% endif %}
    </div>
    <p class="text-light p-1">{{ review.review }}</p>
    <p class="small p-1 text-light"> by {{ review.profile_user}} on
        {{ review.created_date|date:"d-m-Y"}}
    </p>
    {% if review.profile_user == request.user or request.user.is_superuser %}
    <div class="text-center">
        <a class="text-left btn btn-light" href="{% url 'edit_review' review.id %}#reviews">
            Edit Review
        </a>
    </div>
    {% endif %}
</div>
</div>

{% empty %}
<div class="text-center mt-5">
    <p>No reviews for this product, you can be the first...</p>
</div>
{% endfor%}
    



           {% endblock %}
           {% block postloadjs %}
           {{ block.super }}
           {% include 'products/includes/quantity_input_script.html' %}
           {% endblock %}

products/templates/products/products.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col mt-lg-0 mt-md-5 mt-sm-5">
            <h1 class="text-center text-light">Products</h1>
        </div>
    </div>
    {% endblock %}

    {% block content %}
    <!-- Sort By -->
    <div class="row mb-3">
        <div class="col-sm-12 col-md-7 ml-lg-5">
            <p class="text-light mt-3 text-left">
                {% if search_term or current_categories or current_sorting != 'None_None' %}
                <span class="small"><a class="site-font text-light" href="{% url 'products' %}"></a> </span>
                {% endif %}
                {{ products|length }} Meals {% if search_term %} found for
                <strong>"{{ search_term }}"</strong>{% endif %}
            </p>
        </div>
        <div
            class="col-sm-12 col-md-6 col-lg-4 my-auto d-flex justify-content-center justify-content-md-end text-light">
            <div class="sort-select-wrapper-sort-by">

                <select class="selectpicker" data-style="btn-light" name="sort-selector" id="sort-selector">
                    <option value="reset" {% if current_sorting == 'None_None' %}selected{% endif %}>Sort by...</option>
                    <option value="price_asc" {% if current_sorting == 'price_asc' %}selected{% endif %}>Price (low to
                        high)</option>
                    <option value="price_desc" {% if current_sorting == 'price_desc' %}selected{% endif %}>Price (high
                        to low)</option>
                    <option value="calories_asc" {% if current_sorting == 'calories_asc' %}selected{% endif %}>Calories
                        (low-high)</option>
                    <option value="calories_desc" {% if current_sorting == 'calories_desc' %}selected{% endif %}>
                        Calories (high- low)</option>
                </select>
            </div>
        </div>
    </div>
    <div class="container-fluid mt-5">
        <div class="row">
            <div class="col text-center mt-3">
                <div class="row row-cols-1 row-cols-md-3 g-4">
                    {% for product in products %}
                    <div class="col-sm-6 col-md-6 col-lg-4 col-xl-3 mb-5">
                        <div class="card h-100" style="width:auto;">
                            {% if product.image %}
                            <img class="card-img-top img-fluid" style="width:auto; height: 13rem;"
                                src="{{ product.image.url }}" alt="{{ product.name }}">
                            {% else %}
                            <img class="card-img-top img-fluid" src="{{ MEDIA_URL }}noimage.png"
                                alt="{{ product.name }}">
                            {% endif %}
                            <div class="card-body text-dark">
                                <h5 class="card-title">{{ product.name }} </h5>
                                <p class="card-price fs-4">£{{ product.price }} </p>
                                <p class=""> <i class="fa-solid fa-weight-scale me-2"></i>{{ product.calories }} Cal</p>

                                <div class="text-center">
                                    {% if request.user.is_superuser %}
                                    <div>
                                        <small class="ml-4">
                                            <a href="{% url 'edit_product' product.id %}"
                                                class="btn btn-sm product-button">Edit</a> |
                                            <a class="btn btn-sm product-button"
                                                href="{% url 'delete_product' product.id %}">Delete</a>
                                        </small>
                                    </div>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="card-footer">
                                <a href="{% url 'product_detail' product.id %}" class="btn btn-lg order-button">More
                                    details</a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
<div class="btt-button">
    <a class="btt-link d-flex h-100">
        <i class="fas fa-arrow-up mx-auto my-3"></i>
    </a>
</div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script>
		$('.btt-link').click(function(e) {
			window.scrollTo(0,0)
		})

	 //Sort By Functionality

        $('#sort-selector').change(function() {
            let selector = $(this);
            let currentUrl = new URL(window.location);

            let selectedVal = selector.val();
            if(selectedVal != "reset"){
                let sort = selectedVal.split("_")[0];
                let direction = selectedVal.split("_")[1];

                currentUrl.searchParams.set("sort", sort);
                currentUrl.searchParams.set("direction", direction);

                window.location.replace(currentUrl);
            } else {
                currentUrl.searchParams.delete("sort");
                currentUrl.searchParams.delete("direction");

                window.location.replace(currentUrl);
            }
        });
    </script>
{% endblock %}